const USER_TYPES = {
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
  ENGINEER: "ENGINEER",
};
const USER_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
};

const TICKET_STATUS = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  BLOCKED: "BLOCKED",
  IN_PROGRESS: "IN PROGRESS",
};

module.exports = {
  USER_TYPES: USER_TYPES,
  USER_STATUS: USER_STATUS,
  TICKET_STATUS: TICKET_STATUS,
};
